name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Verify
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code base
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build multi-stage Docker image
      - name: Build Docker image
        run: |
          docker build --target builder -t service-server-builder .
          docker build -t service-server:latest .

      # Step 4: Run tests in the builder stage
      - name: Run tests
        run: |
          docker run --rm service-server-builder npm test

      # Step 5: Run linting
      - name: Run ESLint
        run: |
          docker run --rm service-server-builder npm run lint

      # Step 6: Verify health check in production container
      - name: Verify health check
        run: |
          docker run -d --name service-server -p 4000:4000 service-server:latest
          sleep 5
          curl -f http://localhost:4000/health
          docker stop service-server