name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    name: Build, Test, and Verify
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code base
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build multi-stage Docker image
      - name: Build Docker image
        run: |
          docker build --target builder -t service-server-builder .
          docker build -t service-server:latest .

      # Step 4: Run tests in the builder stage
      - name: Run tests
        run: |
          docker run --rm service-server-builder npm test

      # Step 5: Verify health check in production container
      - name: Verify health check
        run: |
          docker run -d --name service-server -p 4000:4000 service-server:latest
          sleep 30
          curl -f http://localhost:4000/health
          docker stop service-server

      # Step 6: Scan Docker image with Snyk
      - name: Scan Docker image with Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: service-server:latest
          args: --severity-threshold=high

      # Step 7: Install Conftest
      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.58.0/conftest_0.58.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.58.0_Linux_x86_64.tar.gz -C /usr/local/bin

      # Step 8: Run OPA policies on Dockerfile
      - name: Run OPA policies
        run: |
          conftest test ./dockerfile --policy ./policies/docker.rego

      # Step 9: Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 10: Tag the image
      - name: Tag Docker image
        run: |
          docker tag service-server:latest ghcr.io/${{ github.repository }}:latest

      # Step 11: Sign and Push with Docker Content Trust
      - name: Sign and Push Docker image
        env:
          DOCKER_CONTENT_TRUST: 1
          DOCKER_CONTENT_TRUST_SERVER: https://ghcr.io
          DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: ${{ secrets.DCT_ROOT_PASSPHRASE }}
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.DCT_REPOSITORY_PASSPHRASE }}
        run: |
          docker trust key generate deployer
          docker trust signer add --key deployer.pub deployer ghcr.io/${{ github.repository }}
          docker trust sign ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

      # Step 12: Verify image signature
      - name: Verify Docker image
        env:
          DOCKER_CONTENT_TRUST: 1
          DOCKER_CONTENT_TRUST_SERVER: https://ghcr.io
        run: |
          docker trust inspect ghcr.io/${{ github.repository }}:latest