name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Verify
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code base
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build multi-stage Docker image
      - name: Build Docker image
        run: |
          docker build --target builder -t service-server-builder .
          docker build -t service-server:latest .

      # Step 4: Run tests in the builder stage
      - name: Run tests
        run: |
          docker run --rm service-server-builder npm test

      # Step 5: Verify health check in production container
      - name: Verify health check
        run: |
          docker run -d --name service-server -p 4000:4000 service-server:latest
          sleep 30
          curl -f http://localhost:4000/health
          docker stop service-server

      # Step 6: Scan Docker image with Snyk
      - name: Scan Docker image with Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: service-server:latest
          args: --severity-threshold=high

      # Step 7: Install Conftest
      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.58.0/conftest_0.58.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.58.0_Linux_x86_64.tar.gz -C /usr/local/bin

      # Step 8: Run OPA policies on Dockerfile
      - name: Run OPA policies
        run: |
          conftest test ./dockerfile --policy ./policies/docker.rego

      - name: Install Notation
        run: |
          VERSION="1.1.0"
          curl -Lo notation.tar.gz https://github.com/notaryproject/notation/releases/download/v${VERSION}/notation_${VERSION}_linux_amd64.tar.gz
          tar xvzf notation.tar.gz
          sudo install notation /usr/local/bin/

      - name: Generate Notation Certificate
        run: |
          notation cert generate-test --default "github-actions"

      - name: Sign with Notation
        run: |
          notation sign --key github-actions ghcr.io/${{ github.repository }}:latest
        env:
          NOTATION_USERNAME: ${{ github.actor }}